### ISSUE TITLE
部署最新环境

### ISSUE THREAD

**Issue by cirias** [Tradesparq/albicilla-setup#1]
#### 准备
1. 更新albicilla-setup
1. 安装docker-compose https://docs.docker.com/compose/install/

#### 目录
2. 删除albicilla-api
1. 重命名项目目录albicilla-api-master -> albicilla-api

这时，应该有7个项目，albicilla-api albicilla-api-v4 albicilla-public albicilla-rest albicilla-setup albicila-user gentilis

#### 分支
1. albicilla-rest dev
2. albicilla-user v2.0
3. 其余均为master分支
4. 确保代码最新

#### 清理
1. 删除过时的config文件
2. 运行albicilla-setup/setup-all.sh
3. 删除docker container

#### 启动
2. 在albicilla-setup目录下运行`docker-compose up -d`

#### 日志
1. 通过`docker logs` 查看

**Comment by cirias** [comment]
@edwardrf @itomg @r1N0Xmk2 @fturly @hgdharold

**Comment by r1N0Xmk2** [comment]
部署了，发现连不上api-v4，
[需要改host](https://github.com/Tradesparq/albicilla-setup#edit-hosts)
加上127.0.0.1   api_v4.albicilla.com
